### ISSUE TITLE
Problem with lora_receive_realtime flow

### ISSUE THREAD

**Issue by reletreby** [rpp0/gr-lora#10]
Hi,

Where can I see the decoded data while running the gnuradio flow lora_receive_realtime? I see no output in gnuradio or the terminal. There is just a real-time fft window.

I am actually conducting a real experiment with Semtech LoRa modules and I expect lora_receive_realtime to decode LoRa signals in realtime.

Thanks,
Rashad

**Comment by rpp0** [comment]
Hi, thanks for your question. If a packet is decoded it will be printed to the terminal. So if you don't see anything, then either you misconfigured the spreading factor (SF) or your packet doesn't get detected by gr-lora. Could you send me a sample cfile of what you're trying to decode?
