### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by pcm1702** [rpp0/gr-lora#12]
We tried to compile, but the compiler gives an incompatible function error. With this change in the code we could compile.

--- a/lib/message_file_sink_impl.cc
+++ b/lib/message_file_sink_impl.cc
@@ -701,7 +701,7 @@ namespace gr {
         message_port_register_in(pmt::mp("in"));
         set_msg_handler(pmt::mp("in"), boost::bind(&message_file_sink_impl::msg_handler, this, _1));
 
-        d_file.open(path, std::ios::out | std::ios::binary);
+        d_file.open(path.c_str(), std::ios::out | std::ios::binary);
     }
 
     /*

**Comment by rpp0** [comment]
Hi, thanks for reporting this! It seems older versions of g++ error on this, whereas newer versions do not. I incorporated your suggestion in the latest commit.
