### ISSUE TITLE
recording lora signals

### ISSUE THREAD

**Issue by zahraaghapour** [rpp0/gr-lora#122]
Hi, First of all, thank you for your great work. I am using USRP in the 868.3MHz frequency (sample rate =1M) and I can get the packet correctly. I am trying to get the Lora signal and save it in a file then I want to check some things in the Lora packet like device address then if it is from the desired device, I'll send the saved signal to the gateway(with the same USRP device as TX/RX). (it is for jamming and replay attack)
I can check the device address correctly but my problem is saving the signal for the next step.
I left a file sink block after the USRP block but it doesn't save a valid signal because I can't transmit it. The transmitter is simple - a file source and USRP sink - This is the error I am getting : RuntimeError: LookupError: IndexError: multi_usrp: TX channel 38204752 out of range for configured TX frontends

Can you suggest to me how to save the signal for later transmission?
I am using USRP B210 and Lostik Lora USB device (rn2483)
Thank you in advance.

**Comment by luar-lulu** [comment]
I also encountered a similar problem. Can you tell me how you solved it? Thank you very much.
