### ISSUE TITLE
Missing LoRa module

### ISSUE THREAD

**Issue by MartinPolytech** [rpp0/gr-lora#129]
Hello everyone :)

We are currently working on a lora project and we are having some issues with the installation of gr-lora.  After finishing the installation the lora blocks seem to be missing (as you can see in the lora_receive_file below).

![image](https://user-images.githubusercontent.com/61868659/105976653-bc8f5800-6090-11eb-825a-80e4285c472a.png)

And when we try to execute the file "lora_receive_file_nogui.py" file to test the installation, the terminal says that the lora modules are missing.

![Screenshot from 2021-01-27 11-10-53](https://user-images.githubusercontent.com/61868659/105976872-fb251280-6090-11eb-8375-526fa3ad7263.png)

We have checked at usr/local/lib/python3/dist-packages and the lora folder is missing, could you tell us how to fix this ?

Any help is appreciated :)

**Comment by rpp0** [comment]
Hello, during the execution of `sudo make install` you should see the directory to which the files are copied. My guess is that they are not copied to `/usr/local/lib`. You can specify the install directory with `-DCMAKE_INSTALL_PREFIX=` as indicated in the installation instructions.

**Comment by MartinPolytech** [comment]
Hello,

First of all thank you for the quick answer :) With your advice we managed to install gr-lora correctly.

Howewer when we try to execute the file "lora_receive_file_nogui.py" to test the installation, the following error appears. 

![image](https://user-images.githubusercontent.com/61868659/106123240-fc6e4200-6159-11eb-967e-eebb848f4dc0.png)

Is it and error from us or in the file ?

Thank you again and have a great day !

**Comment by rpp0** [comment]
A while ago, gr-lora transitioned to Python 3. I think I forgot to update this example file. It should work if you use `input` rather than `raw_input`. I'll post a patch this weekend, thanks for reporting!

**Comment by rpp0** [comment]
Fixed in 124f2120ae29583a4ca2d2a5e6cb9eb67c2d1b4e!
