### ISSUE TITLE
AttributeError: 'module' object has no attribute 'lora_receiver'

### ISSUE THREAD

**Issue by 97aditi** [rpp0/gr-lora#36]
It was working all good and then suddenly I got this error.

**Comment by Wosser1sProductions** [comment]
Have you updated dependencies but not recompiled `gr-lora`or something equivalent?
This error would happen if GNURadio cannot find the gr-lora components.

[Try the suggestions on this wiki page.](https://github.com/rpp0/gr-lora/wiki/Common-compile-and-runtime-errors)
