### ISSUE TITLE
Forgotten command for manual installation

### ISSUE THREAD

**Issue by Kiogora** [rpp0/gr-lora#49]
git clone https://github.com/rpp0/gr-lora.git .
**cd gr-lora**
mkdir build
cd build
cmake ../  # Note to Arch Linux users: add "-DCMAKE_INSTALL_PREFIX=/usr"
make && sudo make install

**Comment by rpp0** [comment]
Hi! That would work if there was no dot after gr-lora.git. Currently, the install instructions are correct.
