### ISSUE TITLE
Problem with make in "void decoder_impl::samples_to_file" in "decoder_impl.cc"

### ISSUE THREAD

**Issue by reletreby** [rpp0/gr-lora#5]
You have to use this line
`out_file.open(path.c_str(), std::ios::out | std::ios::binary);`
instead of that line
`out_file.open(path, std::ios::out | std::ios::binary);`
for the make to proceed correctly.

**Comment by rpp0** [comment]
Hi reletreby, thanks for reporting this issue. What version of gcc were you using? With gcc 6.1.1 it should compile without errors, but I will address the problem.

**Comment by rpp0** [comment]
Fixed in 3371396.
