### ISSUE TITLE
Installation issue in mac

### ISSUE THREAD

**Issue by rupamk** [rpp0/gr-lora#52]
Hi,
I am trying to install the package in mac with all dependencies installed. However when I am trying to execute "make", I am facing an error:

[  3%] Building CXX object lib/CMakeFiles/gnuradio-lora.dir/decoder_impl.cc.o
In file included from /Users/gr-lora/lib/decoder_impl.cc:31:
/Users/gr-lora/include/lora/utilities.h:128:29: warning: 
      range-based for loop is a C++11 extension [-Wc++11-extensions]
            for (const T& x : v)
                            ^
In file included from /Users/gr-lora/lib/decoder_impl.cc:32:
/Users/gr-lora/lib/decoder_impl.h:39:14: warning: 
      scoped enumerations are a C++11 extension [-Wc++11-extensions]
        enum class DecoderState {
             ^
/Users/gr-lora/lib/decoder_impl.cc:53:33: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
            d_state = gr::lora::DecoderState::DETECT;
                                ^
/Users/gr-lora/lib/decoder_impl.cc:716:32: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
                case gr::lora::DecoderState::DETECT: {
                               ^
/Users/gr-lora/lib/decoder_impl.cc:716:22: error: 
      expression is not an integral constant expression
                case gr::lora::DecoderState::DETECT: {
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/gr-lora/lib/decoder_impl.cc:724:45: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
                        d_state = gr::lora::DecoderState::SYNC;
                                            ^
/Users/gr-lora/lib/decoder_impl.cc:733:32: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
                case gr::lora::DecoderState::SYNC: {
                               ^
/Users/gr-lora/lib/decoder_impl.cc:733:22: error: 
      expression is not an integral constant expression
                case gr::lora::DecoderState::SYNC: {
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/gr-lora/lib/decoder_impl.cc:744:41: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
                    d_state = gr::lora::DecoderState::FIND_SFD;
                                        ^
/Users/gr-lora/lib/decoder_impl.cc:748:32: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
                case gr::lora::DecoderState::FIND_SFD: {
                               ^
/Users/gr-lora/lib/decoder_impl.cc:748:22: error: 
      expression is not an integral constant expression
                case gr::lora::DecoderState::FIND_SFD: {
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/gr-lora/lib/decoder_impl.cc:762:45: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
                        d_state = gr::lora::DecoderState::PAUSE;
                                            ^
/Users/gr-lora/lib/decoder_impl.cc:771:49: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
                            d_state = gr::lora::DecoderState::DETECT;
                                                ^
/Users/gr-lora/lib/decoder_impl.cc:782:32: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
                case gr::lora::DecoderState::PAUSE: {
                               ^
/Users/gr-lora/lib/decoder_impl.cc:782:22: error: 
      expression is not an integral constant expression
                case gr::lora::DecoderState::PAUSE: {
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/gr-lora/lib/decoder_impl.cc:784:45: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
                        d_state = gr::lora::DecoderState::DECODE_PAYLOAD;
                                            ^
/Users/gr-lora/lib/decoder_impl.cc:787:45: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
                        d_state = gr::lora::DecoderState::DECODE_HEADER;
                                            ^
/Users/gr-lora/lib/decoder_impl.cc:793:32: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
                case gr::lora::DecoderState::DECODE_HEADER: {
                               ^
/Users/gr-lora/lib/decoder_impl.cc:793:22: error: 
      expression is not an integral constant expression
                case gr::lora::DecoderState::DECODE_HEADER: {
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/gr-lora/lib/decoder_impl.cc:817:45: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
                        d_state = gr::lora::DecoderState::DECODE_PAYLOAD;
                                            ^
/Users/gr-lora/lib/decoder_impl.cc:824:32: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
                case gr::lora::DecoderState::DECODE_PAYLOAD: {
                               ^
/Users/gr-lora/lib/decoder_impl.cc:824:22: error: 
      expression is not an integral constant expression
                case gr::lora::DecoderState::DECODE_PAYLOAD: {
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/gr-lora/lib/decoder_impl.cc:839:45: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
                        d_state = gr::lora::DecoderState::DETECT;
                                            ^
/Users/gr-lora/lib/decoder_impl.cc:848:32: warning: 
      use of enumeration in a nested name specifier is a C++11 extension
      [-Wc++11-extensions]
                case gr::lora::DecoderState::STOP: {
                               ^
/Users/gr-lora/lib/decoder_impl.cc:848:22: error: 
      expression is not an integral constant expression
                case gr::lora::DecoderState::STOP: {
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
18 warnings and 7 errors generated.
make[2]: *** [lib/CMakeFiles/gnuradio-lora.dir/decoder_impl.cc.o] Error 1
make[1]: *** [lib/CMakeFiles/gnuradio-lora.dir/all] Error 2
make: *** [all] Error 2

**Comment by rpp0** [comment]
Hi! Unfortunately I don't own a Mac, so I can't help you. Perhaps there's some useful info here: https://trac.macports.org/ticket/54709
