### ISSUE TITLE
Some enquiries on the LoRa encoder and decoder process 

### ISSUE THREAD

**Issue by ll550** [rpp0/gr-lora#53]
Hi mate,

I am so glad to see this gr-lora performing very well in some parameters settings. However,  I found that in your code you have used deinterleave module in the demodulating stage, and then perform deshuffle, dewhitening, and hamming decoding.   This is different from what I am understanding about LoRa. 

1, Is the deshuffle process equivalent to de-gray?
2,I suppose the decoding process should be demod, de-gray(deshuffle?),dewhitening,deinterleaved and hamming decoding. 

Could you please explain a bit more on this part and give me some advice? I want to reproduce the encoder for performance evaluation in more practical scenarios with our own design MAC layers, in which the performance limit of the LoRa must be investigated. For simulation, it would be easier to deploy a large number of LoRa end-devices.

Regards

Alex

**Comment by rpp0** [comment]
Hi Alex, I responded to your question via the email you sent me, so I'm closing this issue.
