### ISSUE TITLE
cannot run the example

### ISSUE THREAD

**Issue by shanggdlk** [rpp0/gr-lora#55]
Hi,

I successfully installed the gr-lora, but when trying to run the example, error happens as follows:

./lora_receive_file_nogui.py 
[?] Download test LoRa signal to decode? [y/N] y
[+] Downloading https://research.edm.uhasselt.be/probyns/lora/usrp-868.1-sf7-cr4-bw125-crc-0.sigmf-data -> ./example-trace.sigmf-data . . . . . . . . . . . . . . . . . .
[+] Downloading https://research.edm.uhasselt.be/probyns/lora/usrp-868.1-sf7-cr4-bw125-crc-0.sigmf-meta -> ./example-trace.sigmf-meta . .
[+] Configuration: 868.1 MHz, SF 7, CR 4/8, BW 125 kHz, prlen 8, crc on, implicit off
[+] Decoding. You should see a header, followed by 'deadbeef' and a CRC 5 times.
Traceback (most recent call last):
  File "./lora_receive_file_nogui.py", line 96, in <module>
    tb = lora_receive_file_nogui(data_file_path, sample_rate, capture_freq, lora_config)
  File "./lora_receive_file_nogui.py", line 30, in __init__
    self.message_socket_sink = lora.message_socket_sink('127.0.0.1', 40868, False, False)
  File "/usr/local/lib/python2.7/dist-packages/lora/lora_swig.py", line 784, in make
    return _lora_swig.message_socket_sink_make(*args, **kwargs)
TypeError: message_socket_sink_make() takes at most 3 arguments (4 given)

Any ideas about that? I'm running on the Ubuntu.14.04

**Comment by rpp0** [comment]
Thanks for reporting. The message socket sink constructor indeed changed in the last update; I forgot to update the example accordingly.

**Comment by rpp0** [comment]
Fixed in c4547e23b15702445622b20802005798dcc50a95
