### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by nilampradhan2** [rpp0/gr-lora#59]
i tried to run python lora_receive_file_nogui.py file, but i got folloing error:

.. gr-lora/apps$ python lora_receive_file_nogui.py 
Traceback (most recent call last):
  File "lora_receive_file_nogui.py", line 11, in <module>
    from lora.loraconfig import LoRaConfig
ImportError: No module named loraconfig

**Comment by rpp0** [comment]
Did you try this in the Docker image or on your local machine?

**Comment by nilampradhan2** [comment]
now it is working.
but after i simulate lora_receive_file.grc, it shows following error:
 return _blocks_swig0.file_source_make(itemsize, filename, repeat)
RuntimeError: can't open file
how to resolve this?
thank you.

**Comment by nilampradhan2** [comment]
its working!
