### ISSUE TITLE
lora_receive_file_nogui not decoding

### ISSUE THREAD

**Issue by trivediravi13** [rpp0/gr-lora#68]
I just installed gr-lora manually on ubuntu and tried to execute lora_receive_file_nogui.py but it doesn't appear to be decoding anything. It just displays all zeros. Kindly have a look at attached screenshot and debug file. It's not working even with realtime signal

![screenshot from 2018-05-28 18-52-12](https://user-images.githubusercontent.com/3748944/40616329-466884c8-62a8-11e8-9e03-d8cb36e86ef2.png)

[grlora_debug.txt](https://github.com/rpp0/gr-lora/files/2045211/grlora_debug.txt)

**Comment by rpp0** [comment]
Does the Docker image work for you? Most issues from Ubuntu users here are due to Ubuntu not providing the latest versions of the dependencies. Perhaps this is the case and the signal processing is a bit different for the older versions, causing your issue. Another possibility is that the input files are corrupted; the md5sums should be:

```
590b57b2989e58da9b38415ca5fb27f2  example-trace.sigmf-meta
80bf6a49ef1bf142b7ff601255114400  example-trace.sigmf-data
```

**Comment by trivediravi13** [comment]
Md5sum looks correct. I first tried with docker but it throws this error and doesn't start
standard_init_linux.go:190: exec user process caused "exec format error"
Should I run on archlinux ?
It's not even working when I use lora_receive_realtime.py or through GRC blocks. However I can see signal being received on FFT Sink GUI.

**Comment by HTRK** [comment]
I have the same issue when using a 32 bit Ubuntu 16 machine. Running lora_receive_file_nogui.py gives zeros in the output. 
However when using a 64 bit machine, everything works perfectly.

**Comment by rpp0** [comment]
@HTRK Thanks for clearing this up! This is likely indeed what @trivediravi13 was experiencing as well.
