### ISSUE TITLE
SyntaxError: invalid syntax in lora_recv.py

### ISSUE THREAD

**Issue by cdjambov** [rpp0/gr-lora#78]
Hello, I am trying to use the project but got this error. 
Tried to find how the file mentioned below is generated, but this is my first gnuradio use.
Used the gnuradio project from the repo. 

Ubuntu 18.04 LTS
GnuRadio companion 3.7.11

**Generating: '/media/arihang/Data/Work/rtl-sdr/lora_recv.py'
Executing: /usr/bin/python -u /media/arihang/Data/Work/rtl-sdr/lora_recv.py
  File "/media/arihang/Data/Work/rtl-sdr/lora_recv.py", line 103
    self.lora_lora_receiver_0.Template error: set_center_freq($self.freq)
                                            ^
SyntaxError: invalid syntax

Done (return code 1)**
Thanks

**Comment by rpp0** [comment]
I'm confused. There shouldn't be any file named `lora_recv.py`, at least not in this project.
