### ISSUE TITLE
Can't get it to work, 

### ISSUE THREAD

**Issue by MagneticsRF** [rpp0/gr-lora#79]
trying to decode lora, I've tried the zip file examples, real time, from a recorded capture, and can't get anything to work in decoding the lora.

Using the ubuntu GNUradio Live disk. 

Lora node is a hrf95 using the lora lmic library. 

Executing: /usr/bin/python2 -u /home/ubuntu/gr-lora/apps/lora_receive_realtime.py

linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_003.009.006-0-g122d5f8e

gr-osmosdr v0.1.4-77-g2a2236cc (0.1.5git) gnuradio 3.7.11
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy redpitaya 
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Detached kernel driver
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Exact sample rate is: 1000000.026491 Hz
[R82XX] PLL not locked!
Bits (nominal) per symbol: 	5.5
Bins per symbol: 	2048
Samples per symbol: 	16384
Decimation: 		8

**Comment by rpp0** [comment]
Are you running `gr-lora` from the Docker container? Does running `apps/lora_receive_file_nogui.py` work for you?
