### ISSUE TITLE
Problem with lora_receive_realtime.py

### ISSUE THREAD

**Issue by reletreby** [rpp0/gr-lora#9]
Hello,

I am always getting this error while lora_receiver.py. The error is:
"Module has no attribute decode" referring to
``self.c_decoder=lora.decoder(sf)``

I get this on Cmake:
``disabling swig because version check failed``

Thanks,
Rashad

**Comment by rpp0** [comment]
Hi, thanks for reporting the issue. Could you please post the full output of 'cmake ../'? Do you have the 'swig' package installed?

**Comment by reletreby** [comment]
Thanks!

I solved the problem. I had to install the most recent version of swig.
